src/Entity/Interventions.php
<?php

namespace App\Entity;

use App\Repository\InterventionsRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: InterventionsRepository::class)]
class Interventions
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private ?int $id_int = null;

    #[ORM\ManyToOne(targetEntity: Bornes::class)]
    #[ORM\JoinColumn(name: 'id', referencedColumnName: 'id')]
    private ?Bornes $borne;

    #[ORM\Column(type: 'integer')]
    private ?int $id_emp;

    #[ORM\Column(type: 'date')]
    private ?\DateTimeInterface $Date;

    #[ORM\Column(type: 'string', length: 255)]
    private ?string $Type;

    // Getters and setters
    public function getIdInt(): ?int
    {
        return $this->id_int;
    }

    public function getBorne(): ?Bornes
    {
        return $this->borne;
    }

    public function setBorne(?Bornes $borne): self
    {
        $this->borne = $borne;

        return $this;
    }

    public function getIdEmp(): ?int
    {
        return $this->id_emp;
    }

    public function setIdEmp(?int $id_emp): self
    {
        $this->id_emp = $id_emp;

        return $this;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->Date;
    }

    public function setDate(?\DateTimeInterface $Date): self
    {
        $this->Date = $Date;

        return $this;
    }

    public function getType(): ?string
    {
        return $this->Type;
    }

    public function setType(?string $Type): self
    {
        $this->Type = $Type;

        return $this;
    }
}

src/Form/InterventionsType.php
<?php

namespace App\Form;

use App\Entity\Interventions;
use App\Entity\Bornes;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Validator\Constraints\GreaterThanOrEqual;


class InterventionsType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('id_emp')
            ->add('Date', null, [
                'constraints' => [
                    new GreaterThanOrEqual([
                        'value' => 'today', // Set the value to 'today' for current date
                        'message' => 'The date cannot be in the past.',
                    ]),
                ]])
            ->add('Type', ChoiceType::class, [
                'choices' => [
                    'Maintenance' => 'maintenance',
                    'Installation' => 'installation',
                    'Désinstallation' => 'desinstallation',
                ]])
            ->add('borne', EntityType::class, [
                'class' => Bornes::class,
                'choice_label' => 'description', // Field from the Borne entity to display in the dropdown
                'placeholder' => 'Choose a Borne', // Optional: Add a placeholder text
            ]);
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Interventions::class,
        ]);
    }
}

src/Controller/InterventionsController.php
<?php

namespace App\Controller;

use App\Entity\Interventions;
use App\Form\InterventionsType;
use App\Repository\InterventionsRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/interventions')]
class InterventionsController extends AbstractController
{
    #[Route('/', name: 'app_interventions_index', methods: ['GET'])]
    public function index(InterventionsRepository $interventionsRepository): Response
    {
        return $this->render('interventions/index.html.twig', [
            'interventions' => $interventionsRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_interventions_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $intervention = new Interventions();
        $form = $this->createForm(InterventionsType::class, $intervention);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($intervention);
            $entityManager->flush();

            return $this->redirectToRoute('app_interventions_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('interventions/new.html.twig', [
            'intervention' => $intervention,
            'form' => $form,
        ]);
    }

    #[Route('/{id_int}', name: 'app_interventions_show', methods: ['GET'])]
    public function show(Interventions $intervention): Response
    {
        return $this->render('interventions/show.html.twig', [
            'intervention' => $intervention,
        ]);
    }

    #[Route('/{id_int}/edit', name: 'app_interventions_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Interventions $intervention, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(InterventionsType::class, $intervention);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_interventions_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('interventions/edit.html.twig', [
            'intervention' => $intervention,
            'form' => $form,
        ]);
    }

    #[Route('/{id_int}', name: 'app_interventions_delete', methods: ['POST'])]
    public function delete(Request $request, Interventions $intervention, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$intervention->getIdint(), $request->request->get('_token'))) {
            $entityManager->remove($intervention);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_interventions_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/interventions/_delete_form.html.twig
<form method="post" action="{{ path('app_interventions_delete', {'id_int': intervention.idInt}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ intervention.idInt) }}">
    <button class="btn">Delete</button>
</form>

templates/interventions/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/interventions/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Interventions{% endblock %}

{% block body %}
    <h1>Edit Interventions</h1>

    {{ include('interventions/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_interventions_index') }}">back to list</a>

    {{ include('interventions/_delete_form.html.twig') }}
{% endblock %}

templates/interventions/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}liste des interventions{% endblock %}

{% block body %}
    <h1>Liste des interventions</h1>

    <table class="table">
        <thead>
            <tr>
                
                <th>Date</th>
                <th>Type</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for intervention in interventions %}
            <tr>
                
                <td>{{ intervention.Date ? intervention.Date|date('Y-m-d') : '' }}</td>
                <td>{{ intervention.Type }}</td>
                <td>
                    <a href="{{ path('app_interventions_show', {'id_int': intervention.idInt}) }}">show</a>
                    <a href="{{ path('app_interventions_edit', {'id_int': intervention.idInt}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="5">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_interventions_new') }}">Create new</a>
{% endblock %}

templates/interventions/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Interventions{% endblock %}

{% block body %}
    <h1>Create new Interventions</h1>

    {{ include('interventions/_form.html.twig') }}

    <a href="{{ path('app_interventions_index') }}">back to list</a>
{% endblock %}

templates/interventions/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Interventions{% endblock %}

{% block body %}
    <h1>Interventions</h1>

    <table class="table">
        <tbody>
            
            <tr>
                <th>Date</th>
                <td>{{ intervention.Date ? intervention.Date|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Type</th>
                <td>{{ intervention.Type }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_interventions_index') }}">back to list</a>

    <a href="{{ path('app_interventions_edit', {'id_int': intervention.idInt}) }}">edit</a>

    {{ include('interventions/_delete_form.html.twig') }}
{% endblock %}